Karellen.Web/Models/Ocorrencia/NovaOcorrenciaVM.cs
using Karellen.Core.Dominio.Entidade;
using Karellen.Data.Entidade;
using Karellen.Negocio.Mensagem;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Karellen.Web.Models.Ocorrencia
{
    public class NovaOcorrenciaVM
    {
        public int Id { get; set; }
        [Required]
        [DisplayName(@"Título")]
        [MaxLength(30, ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MN019")]
        public string Titulo { get; set; }
        [Required]
        [DisplayName(@"Data e Hora")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd h:mm:ss tt}")]
        public DateTime DataAcontecimento { get; set; }
        [DisplayName(@"Tipo de Ocorrência")]
        public ICollection<EnumTipoOcorrencia> TipoOcorrencias { get; set; }
        [DisplayName(@"Sexo da Vítima")]
        public Sexo SexoVitima { get; set; }
        public string Detalhes { get; set; }
        [DisplayName(@"Fez Boletim de Ocorrência")]
        public bool? TemBoletimOCorrencia { get; set; }
        [DisplayName(@"Autor")]
        public bool OcorrenciaAnonima { get; set; }
        [Required]
        public string Latitude { get; set; }
        [Required]
        public string Longitude { get; set; }

        private Guid _sessaoId;
        public Guid SessaoId
        {
            get { return _sessaoId == default(Guid) ? Guid.NewGuid() : _sessaoId; }
            set { _sessaoId = value; }
        }
    }
}

Karellen.Web/Controllers/OcorrenciaController.cs
using AutoMapper;
using GeoJSON.Net.Geometry;
using Karellen.Negocio.Interface;
using Karellen.Negocio.Mensagem.Enum;
using Karellen.Negocio.Util.DTO;
using Karellen.Web.Filtro;
using Karellen.Web.Models.Ocorrencia;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using GeoJSON.Net.Feature;
using Microsoft.Practices.Unity;

namespace Karellen.Web.Controllers
{
    [Authorize]
    public class OcorrenciaController : BaseController
    {
        private readonly IOcorrenciaServico _servico;

        public string IdOperacao { get; set; }

        public OcorrenciaController(IOcorrenciaServico servico)
        {
            _servico = servico;
            IdOperacao = "IdOperacao";
        }


        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Nova()
        {
            ViewBag.Acao = "Nova";
            return View("Nova", new NovaOcorrenciaVM());
        }

        [Log]
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Nova(NovaOcorrenciaVM model)
        {
            if (!ModelState.IsValid) return View("Nova");

            var ocorrencia = Mapper.Map<NovaOcorrenciaVM, OcorrenciaDTO>(model);

            if (User.Identity.IsAuthenticated && !model.OcorrenciaAnonima)
            {
                ocorrencia.UsuarioId = User.Identity.GetUserId<int>();
            }
            var idOperacaoLog = Session[IdOperacao];
            var resultado = _servico.SalvarNovaOcorrencia(ocorrencia, idOperacaoLog);

            ViewBag.Acao = "Nova";

            return RedirectToAction("index", "app", new {mensagem = EnumMensagem.OcorrenciaCriada});
        }

        [HttpGet]
        public ActionResult Coordenadas()
        {
            var ocorrencias = _servico.BuscarTodasOcorrencias();
            var featureCollection = new FeatureCollection();

            var c = ocorrencias.Select(o =>
                new Feature
                (new Point
                    (new GeographicPosition(o.Latitude, o.Longitude)), new
                {
                    UsuarioId = User.Identity.GetUserId<int>() == o.UsuarioId ? o.UsuarioId : null,
                    o.Id,
                    Nome = o.Titulo,
                    Data = o.DataAcontecimento.ToString("D", DateTimeFormatInfo.CurrentInfo),
                    o.Detalhes
                }));

            featureCollection.Features.AddRange(c);
            var coordenadasSerializadas = JsonConvert.SerializeObject(featureCollection, Formatting.Indented);

            return GeoJson(coordenadasSerializadas);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Coordenada(int id)
        {
            var ocorrencia = _servico.BuscarOcorrencia(id);
            var featureCollection = new FeatureCollection();

            var c = new Feature
                (new Point (new GeographicPosition(ocorrencia.Latitude, ocorrencia.Longitude)), new
                    {
                        UsuarioId = User.Identity.GetUserId<int>() == ocorrencia.UsuarioId ? ocorrencia.UsuarioId : null,
                    ocorrencia.Id,
                        Nome = ocorrencia.Titulo,
                        Data = ocorrencia.DataAcontecimento.ToString("D", DateTimeFormatInfo.CurrentInfo),
                    ocorrencia.Detalhes
                    });

            featureCollection.Features.Add(c);
            var coordenadasSerializadas = JsonConvert.SerializeObject(featureCollection, Formatting.Indented);

            return GeoJson(coordenadasSerializadas);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Detalhes(int id)
        {
            var ocorrencia = _servico.BuscarOcorrencia(id);
            var model = Mapper.Map<OcorrenciaDTO, NovaOcorrenciaVM>(ocorrencia);
            var autor = _servico.BuscarAutorOcorrencia(id);

            ViewBag.Autor = autor == null ? "Ocorrência Anônima" : autor.NomeCompleto;
            ViewBag.AutorId = autor?.Id;

            return View("Detalhes", model);
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Editar(int id)
        {
            var ocorrencia = _servico.BuscarOcorrencia(id);
            var model = Mapper.Map<OcorrenciaDTO, NovaOcorrenciaVM>(ocorrencia);
            model.OcorrenciaAnonima = ocorrencia.UsuarioId == null;
            ViewBag.Acao = "Editar";
            return View("Nova", model);
        }

        [Log]
        [HttpPost]
        public ActionResult Editar(NovaOcorrenciaVM model)
        {
            if (!ModelState.IsValid) { return View("Nova"); }

            var dto = Mapper.Map<NovaOcorrenciaVM, OcorrenciaDTO>(model);

            if (model.OcorrenciaAnonima)
            {
                dto.UsuarioId = null;
            }

            if (User.Identity.IsAuthenticated && !model.OcorrenciaAnonima)
            {
                dto.UsuarioId = User.Identity.GetUserId<int>();
            }


            var idOperacaoLog = Session[IdOperacao];
            _servico.AtualizarOcorrencia(dto, idOperacaoLog);


            return RedirectToAction("index", "app", new {mensagem = EnumMensagem.Alterado});
        }

        [HttpPost]
        public ActionResult Excluir(int id)
        {
            var ocorrencia = _servico.BuscarOcorrencia(id);
            if (ocorrencia.UsuarioId != User.Identity.GetUserId<int>())
            {
                return RedirectToAction("index", "app", new {mensagem = EnumMensagem.ErroPermissao});
            }

            _servico.ExcluirOcorrencia(id);
            return RedirectToAction("index", "app", new { mensagem = EnumMensagem.Alterado });
        }
        [HttpPost]
        public ActionResult Solucionar(int id, string solucao)
        {
            var o = _servico.BuscarOcorrencia(id);
            if (o.UsuarioId != User.Identity.GetUserId<int>())
            {
                return View();
            }

            _servico.SolucionarOcorrencia(id, solucao);

            return RedirectToAction("index", "app", new {mensagem = EnumMensagem.Alterado});
        }
    }
}

Karellen.Web/Views/Ocorrencia/Detalhes.cshtml
@using Karellen.Negocio.Util.Extensao
@using Karellen.Web.Helper
@using Microsoft.AspNet.Identity
@model Karellen.Web.Models.Ocorrencia.NovaOcorrenciaVM
@{
    ViewBag.Title = Model.Titulo + " - Detalhes";
}
@section css {
    <meta property="og:title" content="@Model.Titulo">
    <meta property="og:site_name" content="Karellen">
    <meta property="og:description" content="@Model.Detalhes">
}
<div id="sidewrapper">
    <div class="sidebar">
        <div class="heading" id="titulo">
            <h1>Detalhes</h1>
        </div>
        <div id="listingsocorrencia" class="listings">
           
            <div class="item">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label", placeholder = "O Título da ocorrência" })
                <div>
                    @Html.DisplayFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="item">
                @Html.LabelFor(model => model.DataAcontecimento, htmlAttributes: new { @class = "control-label" })
                <div>
                    <div class='input-group date' id='datetimepicker1'>
                        <label class="control-label">@Model.DataAcontecimento.ToString("f")</label>
                    </div> 
                </div>
            </div>
            <div class="item">
                @Html.LabelFor(model => model.Detalhes, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.DisplayFor(model => model.Detalhes, new { @class = "form-control" })
                </div>
            </div>
            <div class="item">
                <label class="control-label">Sexo da vítima: *</label>
                <div>
                    @Html.RadioButtonFor(model => model.SexoVitima, "Feminino", new { disabled = "disabled" })
                    Feminino

                    @Html.RadioButtonFor(model => model.SexoVitima, "Masculino", new { disabled = "disabled" })
                    Masculino
                </div>
            </div>
            <div class="item">
                @Html.LabelFor(model => model.TemBoletimOCorrencia, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.RadioButtonFor(m => m.TemBoletimOCorrencia, "true", new { disabled = "disabled" })<span> Sim</span>
                    @Html.RadioButtonFor(m => m.TemBoletimOCorrencia, "false", new { disabled = "disabled" })<span> Não</span>

                </div>
            </div>
            <div class="item">
                @Html.LabelFor(m => m.TipoOcorrencias)
                <div>
                    @foreach (var tipo in Model.TipoOcorrencias)
                    {
                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                        @tipo.GetDescricao()
                    }
                </div>
            </div>
            <div class="item">
                <label class="control-label">Autor: </label>
                @{
                    var autor = Model.OcorrenciaAnonima ? "Ocorrência Anônima" : ViewBag.Autor as string;
                }
                <h5 class="autor">@autor</h5>
                    @if (ViewBag.AutorId == User.Identity.GetUserId<int>())
                    {
                        <button type="button" data-toggle="modal" data-hidden="@Model.Id" data-target="#myModal" style="margin-left:1em; color:white;" class="btn btn-primary btn-default btnsaibamais autor">
                            <i class="fa fa-check" aria-hidden="true"></i> Solucionar
                        </button>
                    }
            </div>
            <div class="item" style="margin-bottom: 10em;">
                <h3>Compartilhe</h3>
                <div>
                    <a href=https://plus.google.com/share?url=@Request.Url target="_blank" class="btn btn-lg btn-block btn-google first-letter" id="homegoogle" name="provider" value="google">
                        <i class="fa fa-google visible-xs"></i>
                        <span class="hidden-xs">google</span>
                    </a>
                    <a href=https://facebook.com/sharer.php?u=@Request.Url target="_blank" class="btn btn-lg btn-block btn-facebook first-letter" id="homefacebook" name="provider" value="facebook">
                        <i class="fa fa-google visible-xs"></i>
                        <span class="hidden-xs">facebook</span>
                    </a>
                </div>
            </div>
            </div>
          
        </div>
    </div>

<div id="mapa" class="map"></div>

@section scripts {
    <script src="~/Content/karellen/js/Ocorrencia/detalhes.js"></script>
    <script src="~/Content/karellen/js/Global/navegacao.js" type="text/javascript"></script>
}

Karellen.Web/Views/Ocorrencia/Nova.cshtml
@using Karellen.Web.Helper
@model Karellen.Web.Models.Ocorrencia.NovaOcorrenciaVM
@{
    ViewBag.Title = "Nova Ocorrência";
    var acao = ViewBag.Acao as string;
}

<div id="sidewrapper">
    <div class="sidebar">
        <div class="heading" id="titulo">
            <h1>@acao Ocorrência</h1>
        </div>
        <div id="listingsocorrencia" class="listings">
            @using (Html.BeginForm(acao, "Ocorrencia", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                @Html.HiddenFor(m => m.Latitude)
                @Html.HiddenFor(m => m.Longitude)
                @Html.HiddenFor(m => m.SessaoId)

                <div class="form-horizontal form-espacado">
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <div class="form-group listings item">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label", placeholder = "O Título da ocorrência" })
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group item ">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.DataAcontecimento, htmlAttributes: new { @class = "control-label" })
                            <div class='input-group date' id='datetimepicker1'>
                                @Html.TextBoxFor(model => model.DataAcontecimento, new { @class = "form-control datepicker" })
                                <span class="input-group-addon" id="datetimepicker">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group listings item">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.Detalhes, htmlAttributes: new { @class = "control-label" })
                            @Html.TextAreaFor(model => model.Detalhes, new { @class = "form-control", rows = 10 })
                        </div>
                    </div>

                    <div class="form-group listings item">
                        <div class="col-md-12">
                            <label class="control-label">Sexo da vítima: *</label>

                            @Html.RadioButtonFor(model => model.SexoVitima, "Feminino")
                            Feminino

                            @Html.RadioButtonFor(model => model.SexoVitima, "Masculino")
                            Masculino
                        </div>
                    </div>

                    <div class="form-group listings item">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.TemBoletimOCorrencia, htmlAttributes: new { @class = "control-label" })
                            @Html.RadioButtonFor(m => m.TemBoletimOCorrencia, "true")<span> Sim</span>
                            @Html.RadioButtonFor(m => m.TemBoletimOCorrencia, "false")<span> Não</span>
                        </div>
                    </div>
                    <div class="form-group item">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.TipoOcorrencias, htmlAttributes: new { @class = "control-label" })<span> *</span>
                            @Html.OcorrenciasFor(model => model.TipoOcorrencias, new { @class = "chosen-select", data_placeholder = "Escolha o tipo de ocorrência" });
                        </div>
                    </div>


                    <div class="form-group listings item">
                        <div class="col-md-12" style="text-align: center">
                            <label class="control-label">Autor: </label>
                            @Html.OcorrenciaAnonimaFor(model => model.OcorrenciaAnonima, User.Identity.IsAuthenticated, usuarioNome: Session["NomeUsuario"] as string)
                        </div>
                    </div>

                    <div class="form-group  listings item" style="margin-bottom: 15em;">
                        <div class="col-md-12" style="text-align: center">
                            <input type="submit" value="@acao" class="btn btn-default btn-lg btn-primary" id="btn-submit" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div id="mapa" class="map"></div>

@section scripts {
    <script src="~/Content/karellen/js/Global/navegacao.js" type="text/javascript"></script>
    <script src="~/Content/karellen/js/Ocorrencia/nova.js" type="text/javascript"></script>
}